=== HULCBio/MotionStation/bin/registry/FunctionRegistry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:mathworks.dispatcher.registry"
	    xmlns="urn:mathworks.dispatcher.registry" 
	    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	    elementFormDefault="qualified">

    <xsd:simpleType name="MatlabModnameType">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="80"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="MatlabNameType">
        <xsd:restriction base="xsd:string">
            <xsd:maxLength value="63"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="MatlabValueType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value=":all:"/>
            <xsd:enumeration value="double"/>
            <xsd:enumeration value="single"/>
            <xsd:enumeration value="logical"/>
            <xsd:enumeration value="char"/>
            <xsd:enumeration value="cell"/>
            <xsd:enumeration value="struct"/>
            <xsd:enumeration value="int8"/>
            <xsd:enumeration value="uint8"/>
            <xsd:enumeration value="int16"/>
            <xsd:enumeration value="uint16"/>
            <xsd:enumeration value="int32"/>
            <xsd:enumeration value="uint32"/>
            <xsd:enumeration value="int64"/>
            <xsd:enumeration value="uint64"/>
            <xsd:enumeration value="opaque"/>
            <xsd:enumeration value="function_handle"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="MatrixShapeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="0"/>
            <xsd:enumeration value="R"/>
            <xsd:enumeration value="C"/>
            <xsd:enumeration value="2"/>
            <xsd:enumeration value="3"/>
            <xsd:enumeration value="4"/>
            <xsd:enumeration value="N"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="MatlabDatumWidthType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="ptr"/>
            <xsd:enumeration value="8"/>
            <xsd:enumeration value="16"/>
            <xsd:enumeration value="32"/>
            <xsd:enumeration value="64"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="FcnRegistrationType">
        <xsd:attribute name="name" type="MatlabNameType"/>
        <xsd:attribute name="type" type="MatlabValueType" use="optional"/>
        <xsd:attribute name="complexity" type="xsd:boolean" use="optional"/>
        <xsd:attribute name="full" type="xsd:boolean" use="optional"/>
        <xsd:attribute name="shape" type="MatrixShapeType" use="optional"/>
        <xsd:attribute name="Mvalue" type="xsd:boolean" use="optional"/>
        <xsd:attribute name="jit_signature" type="xsd:string" use="optional"/>
        <xsd:attribute name="nargin" type="xsd:unsignedInt" use="optional"/>
        <xsd:attribute name="nargout" type="xsd:unsignedInt" use="optional"/>
        <xsd:attribute name="reqin" type="xsd:unsignedInt" use="optional"/>
        <xsd:attribute name="reqout" type="xsd:unsignedInt" use="optional"/>
        <xsd:attribute name="varargin" type="xsd:unsignedInt" use="optional"/>
        <xsd:attribute name="varargout" type="xsd:unsignedInt" use="optional"/>
        <xsd:attribute name="width" type="MatlabDatumWidthType" use="optional"/>
        <xsd:attribute name="signed" type="xsd:boolean" use="optional" default="true"/>
        <xsd:attribute name="toolbox_location" type="xsd:string" use="optional"/>
        <xsd:attribute name="extension" type="xsd:string" use="optional"/>
        <xsd:attribute name="precedence" type="xsd:string" use="optional"/>
        <xsd:attribute name="target" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:unsignedInt" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="FcnRegistryType">
        <xsd:sequence>
            <xsd:element name="FcnRegistration" type="FcnRegistrationType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="modname" type="MatlabModnameType" use="optional" />
	<xsd:attribute name="checksum" type="xsd:unsignedInt" use="optional" />
	<xsd:attribute name="creation_time" type="xsd:unsignedInt" use="optional" />
    </xsd:complexType>
    <xsd:element name="FcnRegistry" type="FcnRegistryType" />

</xsd:schema>

=== HULCBio/MotionStation/bin/registry/libmex.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 ! @(#)libmex.xml    generated by: makefcntable 4.1   Sun Apr 11 02:58:23 2004
 -->

<FcnRegistry xmlns="urn:mathworks.dispatcher.registry"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="urn:mathworks.dispatcher.registry
FunctionRegistry.xsd"
             modname="libmex"
             checksum="0xcf6a4ccd"
             creation_time="0x4078ec8f"
             >

<FcnRegistration
          name = ""
          extension = "mexglx"
          precedence = "0xb000"
          target = "glnx86"
 />

<FcnRegistration
          name = ""
          extension = "mexi64"
          precedence = "0xb000"
          target = "glnxi64"
 />

<FcnRegistration
          name = ""
          extension = "mexa64"
          precedence = "0xb000"
          target = "glnxa64"
 />

<FcnRegistration
          name = ""
          extension = "mexhpux"
          precedence = "0xb001"
          target = "hpux"
 />

<FcnRegistration
          name = ""
          extension = "mexhp7"
          precedence = "0xb000"
          target = "hpux"
 />

<FcnRegistration
          name = ""
          extension = "mexmac"
          precedence = "0xb000"
          target = "mac"
 />

<FcnRegistration
          name = ""
          extension = "mexsol"
          precedence = "0xb000"
          target = "sol2"
 />

<FcnRegistration
          name = ""
          extension = "dll"
          precedence = "0xb001"
          target = "win32"
 />

<FcnRegistration
          name = ""
          extension = "mex"
          precedence = "0xb000"
          target = "win32"
 />

<FcnRegistration
          name = ""
          extension = "mexw64"
          precedence = "0xb000"
          target = "win64"
 />

</FcnRegistry>

=== HULCBio/MotionStation/Matlab/bin/registry/jmi.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
 ! @(#)jmi.xml    generated by: makefcntable 4.1   Fri Apr 30 01:24:03 2004
 -->

<FcnRegistry xmlns="urn:mathworks.dispatcher.registry"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="urn:mathworks.dispatcher.registry
FunctionRegistry.xsd"
             modname="jmi"
             checksum="0x27de456c"
             creation_time="0x4091e2f3"
             >

<FcnRegistration
          name = "isjava"
          type = ":all:"
          Mvalue = "false"
          toolbox_location = "matlab/datatypes"
 />

<FcnRegistration
          name = "javaObject"
          type = ":all:"
          Mvalue = "false"
          toolbox_location = "matlab/datatypes"
 />

<FcnRegistration
          name = "java_object"
          type = ":all:"
          Mvalue = "false"
 />

<FcnRegistration
          name = "javaMethod"
          type = ":all:"
          Mvalue = "false"
          toolbox_location = "matlab/datatypes"
 />

<FcnRegistration
          name = "java_method"
          type = ":all:"
          Mvalue = "false"
 />

<FcnRegistration
          name = "javaArray"
          type = "char"
          Mvalue = "false"
          toolbox_location = "matlab/datatypes"
 />

<FcnRegistration
          name = "java_array"
          type = "char"
          Mvalue = "false"
 />

</FcnRegistry>
